# Generated by Django 5.1.4 on 2025-04-11 17:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('usermanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
