# Generated by Django 5.1.4 on 2025-04-12 18:16

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('usermanage', django.db.models.manager.Manager()),
            ],
        ),
    ]
