# Generated by Django 5.1.4 on 2025-05-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
